{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80fad0bb-c371-4bcf-b1f2-f5af281e8813",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-06-03 13:54:42,830 Starting Bokeh server version 3.4.1 (running on Tornado 6.3.3)\n",
      "2024-06-03 13:54:42,832 Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly\n",
      "2024-06-03 13:54:42,832 User authentication hooks NOT provided (default user enabled)\n",
      "2024-06-03 13:54:42,836 Bokeh app running at: http://0.0.0.0:5000/app\n",
      "2024-06-03 13:54:42,836 Starting Bokeh server with process id: 50084\n",
      "2024-06-03 13:54:50,014 WebSocket connection opened\n",
      "2024-06-03 13:54:50,014 ServerConnection created\n"
     ]
    }
   ],
   "source": [
    "!panel serve app.py --allow-websocket-origin=* --port 5000 --address 0.0.0.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "3ee29d26-c6fb-4dba-b461-7de9433f1398",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-05-24 11:08:18,871 Starting Bokeh server version 3.4.1 (running on Tornado 6.3.3)\n",
      "2024-05-24 11:08:18,872 User authentication hooks NOT provided (default user enabled)\n",
      "2024-05-24 11:08:18,876 Bokeh app running at: http://0.0.0.0:5000/app\n",
      "2024-05-24 11:08:18,876 Starting Bokeh server with process id: 48418\n",
      "Creating map figure...\n",
      "Using tile source URL: https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png\n",
      "Tile source added to plot.\n",
      "2024-05-24 11:08:20,155 WebSocket connection opened\n",
      "2024-05-24 11:08:20,156 ServerConnection created\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 11.0 date_begin= 2024-04-24 date_end= 2024-05-24 scale= 30 min station_amount= 1\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|███████████████████████████████████| 2880/2880 [00:00<00:00, 689356.59it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:08:27,053 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-04-24 date_end= 2024-05-24 scale= 30 min station_amount= 1\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|███████████████████████████████████| 2880/2880 [00:00<00:00, 474007.04it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:08:50,838 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-04-24 date_end= 2024-05-24 scale= 30 min station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|███████████████████████████████████| 2880/2880 [00:00<00:00, 813386.00it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:09:02,185 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-02-01 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|█████████████████████████████████| 10848/10848 [00:00<00:00, 888355.85it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:09:21,193 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-05-24 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "2024-05-24 11:09:38,399 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Samma start och slutdatum')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 134, in run_program\n",
      "    start_stop_list = rain_data.divide_time(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/rain_data.py\", line 160, in divide_time\n",
      "    raise ValueError(\"Samma start och slutdatum\")\n",
      "ValueError: Samma start och slutdatum\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2025-04-02 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "2024-05-24 11:09:53,750 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Slutdatum senare än startdatum')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 134, in run_program\n",
      "    start_stop_list = rain_data.divide_time(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/rain_data.py\", line 157, in divide_time\n",
      "    raise ValueError(\"Slutdatum senare än startdatum\")\n",
      "ValueError: Slutdatum senare än startdatum\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2023-03-01 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|█████████████████████████████████| 43200/43200 [00:00<00:00, 477179.00it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:10:08,591 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "^C\n",
      "\n",
      "Interrupted, shutting down\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4e7ec546-f85a-43dc-9736-5ce0aef62e8f",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-05-24 09:41:02,443 Starting Bokeh server version 3.4.1 (running on Tornado 6.3.3)\n",
      "2024-05-24 09:41:02,445 User authentication hooks NOT provided (default user enabled)\n",
      "2024-05-24 09:41:02,448 Bokeh app running at: http://0.0.0.0:5000/app\n",
      "2024-05-24 09:41:02,448 Starting Bokeh server with process id: 46838\n",
      "2024-05-24 09:41:17,268 Error running application handler <panel.io.handlers.ScriptHandler object at 0x7f3c6b1eb310>: No module named 'widgets'\n",
      "File 'app.py', line 6, in <module>:\n",
      "from widgets.signal_selection_widget import SignalSelectionWidget Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/handlers.py\", line 358, in run\n",
      "    exec(self._code, module.__dict__)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 6, in <module>\n",
      "    from widgets.signal_selection_widget import SignalSelectionWidget\n",
      "ModuleNotFoundError: No module named 'widgets'\n",
      " \n",
      "2024-05-24 09:41:17,506 WebSocket connection opened\n",
      "2024-05-24 09:41:17,507 ServerConnection created\n",
      "^C\n",
      "\n",
      "Interrupted, shutting down\n"
     ]
    }
   ],
   "source": [
    "!panel serve app.py --allow-websocket-origin=\"t-app1-560ip-berakning-test.apps.ocpint.gbgpaas.se\" --port 5000 --address 0.0.0.0 #-basic-auth credentials.json #--logout-template templates/login.html #--basic-login-template templates/login.html --cookie-secret my_super_safe_cookie_secret\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "baf3c500-dad7-4e71-b23c-b6e277cfba89",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "!panel serve app.py --allow-websocket-origin=\"t-app2-560ip-berakning-test.apps.ocpint.gbgpaas.se\" --port 8080 --address 0.0.0.0 --admin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a05a75f-fdef-42fd-8e9c-7ca1776e0f45",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "!pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99f00a49-842a-48f3-ad78-9fafa7190904",
   "metadata": {},
   "outputs": [],
   "source": [
    "# tidigare dependencies\n",
    "#!pip install panel bokeh==3.3.4 ipython-sql openpyxl folium psycopg2\n",
    "#!pip install panel>=0.12.6 param>=1.12.0 pandas matplotlib"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
